export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_CART_LENGTH = 'INCREMENT_CART_LENGTH';
export const DECREMENT_CART_LENGTH = 'DECREMENT_CART_LENGTH';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';